# Create the desktop shortcut "DeepSeek Harness" and (by default) a startup
# shortcut that keeps the background server alive after login, so the app
# window opens instantly.
# Usage: powershell -NoProfile -ExecutionPolicy Bypass -File install-shortcut.ps1 [-NoAutoStart]
param([switch]$NoAutoStart)
$ErrorActionPreference = 'Stop'

$desktop = [Environment]::GetFolderPath('Desktop')
$startup = [Environment]::GetFolderPath('Startup')
$shell = New-Object -ComObject WScript.Shell

# Prefer the DeepSeek icon generated by build-icon.ps1; fall back to Edge.
$icon = Join-Path $PSScriptRoot 'deepseek.ico'
if (-not (Test-Path $icon)) {
    $icon = 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe'
    if (-not (Test-Path $icon)) { $icon = 'C:\Program Files\Microsoft\Edge\Application\msedge.exe' }
}

$lnk = $shell.CreateShortcut((Join-Path $desktop 'DeepSeek Harness.lnk'))
$lnk.TargetPath = Join-Path $PSScriptRoot 'dsh-app.bat'
$lnk.WorkingDirectory = $PSScriptRoot
$lnk.IconLocation = "$icon,0"
$lnk.WindowStyle = 7
$lnk.Description = 'DeepSeek Harness desktop launcher'
$lnk.Save()

if (-not $NoAutoStart) {
    $svc = $shell.CreateShortcut((Join-Path $startup 'DSH Background Server.lnk'))
    $svc.TargetPath = 'powershell.exe'
    $svc.Arguments = '-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "' + (Join-Path $PSScriptRoot 'start-server.ps1') + '"'
    $svc.WorkingDirectory = $PSScriptRoot
    $svc.WindowStyle = 7
    $svc.Save()
    Write-Host 'Created: desktop shortcut + startup auto-start (background server).'
} else {
    Write-Host 'Created: desktop shortcut only (no auto-start).'
}
Write-Host 'Done. Double-click "DeepSeek Harness" on your desktop.'
